version: '2'

volumes:
  cloud-orderer.cloudriders.com:
  peer0.my-org1.cloudriders.com:
  peer1.my-org1.cloudriders.com:
  peer0.my-org2.cloudriders.com:
  peer1.my-org2.cloudriders.com:
  peer0.my-org3.cloudriders.com:
  peer1.my-org3.cloudriders.com:
  peer2.my-org3.cloudriders.com:

networks:
  byfn:

services:

  cloud-orderer.cloudriders.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: cloud-orderer.cloudriders.com
    container_name: cloud-orderer.cloudriders.com
    networks:
      - byfn

  peer0.my-org1.cloudriders.com:
    container_name: peer0.my-org1.cloudriders.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.my-org1.cloudriders.com
    networks:
      - byfn

  peer1.my-org1.cloudriders.com:
    container_name: peer1.my-org1.cloudriders.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.my-org1.cloudriders.com
    networks:
      - byfn

  peer0.my-org2.cloudriders.com:
    container_name: peer0.my-org2.cloudriders.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.my-org2.cloudriders.com
    networks:
      - byfn

  peer1.my-org2.cloudriders.com:
    container_name: peer1.my-org2.cloudriders.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.my-org2.cloudriders.com
    networks:
      - byfn

  peer0.my-org3.cloudriders.com:
    container_name: peer0.my-org3.cloudriders.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.my-org3.cloudriders.com
    networks:
      - byfn

  peer1.my-org3.cloudriders.com:
    container_name: peer1.my-org3.cloudriders.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.my-org3.cloudriders.com
    networks:
      - byfn

  peer2.my-org3.cloudriders.com:
    container_name: peer2.my-org3.cloudriders.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.my-org3.cloudriders.com
    networks:
      - byfn

  my-cli:
    container_name: my-cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=my-cli
      - CORE_PEER_ADDRESS=peer0.my-org1.cloudriders.com:17051
      - CORE_PEER_LOCALMSPID=MyOrg1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/my-org1.cloudriders.com/peers/peer0.my-org1.cloudriders.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/my-org1.cloudriders.com/peers/peer0.my-org1.cloudriders.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/my-org1.cloudriders.com/peers/peer0.my-org1.cloudriders.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/my-org1.cloudriders.com/users/Admin@my-org1.cloudriders.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - cloud-orderer.cloudriders.com
      - peer0.my-org1.cloudriders.com
      - peer1.my-org1.cloudriders.com
      - peer0.my-org2.cloudriders.com
      - peer1.my-org2.cloudriders.com
      - peer0.my-org3.cloudriders.com
      - peer1.my-org3.cloudriders.com
      - peer2.my-org3.cloudriders.com
    networks:
      - byfn
