NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.organistaion3.hyper.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.organistaion3.hyper.com-cert.pem
    OrganizationalUnitIdentifier: peer
