NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.my-org3.cloudriders.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.my-org3.cloudriders.com-cert.pem
    OrganizationalUnitIdentifier: peer
